name: Bug Report
description: File a bug report relating to general usage of the GameMaker Cloud services
labels: ["web-bug"]
body:
  - type: markdown
    attributes:
      value: |
        For any GameMaker Account sign-in or licencing issues (including "I can't see all my platforms in Target Manager") please submit a [Helpdesk Ticket](https://contact.gamemaker.io/contact-us#account) instead of using this form.

        Please also ensure you have searched for any existing reports of this issue before you begin - if one exists, please leave a thumbs-up and/or a comment on that one, rather than knowingly filing a duplicate report, as duplicates just slow things down.

        Note that most fields are required to be filled-in before you can submit this report, as it is all essential information which we will require in order to confirm and fix your issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue and do include any relevant screenshots at suitable locations in the body of your text. Please do not add a web link as your entire bug report and assume we will read the external thread to work it out ourselves, as we will most likely simply close the report!
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false

  - type: input
    id: link
    attributes:
      label: Page Link
      description: Please add a link to the relevant page here
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue into the gaps below (add as many steps into the middle as you require)
      value: |
        1. Visit GameMaker Account dashboard
        2. 
        3. 
        4. See the issue
    validations:
      required: true

  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you seeing the problem on?
    validations:
      required: false

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
